Pages/Cursos/Crear.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AplicacionWebRazor.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AplicacionWebRazor.Pages.Cursos
{
    public class Crear : PageModel
    {
        private readonly AppRazorDbContext _Context;
        public Crear(AppRazorDbContext context)
        {
            _Context = context;            
        }
        [BindProperty]
        public Curso curso {get; set;}
        
        public async Task<IActionResult> OnPost()
        {
            if(!ModelState.IsValid){
                return Page();
            }
            curso.FechaCreacion = DateTime.Now;
            _Context.Add(curso);
            await _Context.SaveChangesAsync();
            return RedirectToPage("Index");
        }
    }
}

Pages/Cursos/Editar.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AplicacionWebRazor.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AplicacionWebRazor.Pages.Cursos
{
    public class Editar : PageModel
    {
        private readonly AppRazorDbContext _Context;
        public Editar(AppRazorDbContext context)
        {
            _Context = context;            
        }
        [BindProperty]
        public Curso curso {get; set;}
        
        public async Task OnGet(int Id)
        {
            curso = await _Context.cursos.FindAsync(Id);
        }

         public async Task<IActionResult> OnPost()
        {
            if(ModelState.IsValid){
                var CursoDesdeDb = await _Context.cursos.FindAsync(curso.Id);
                CursoDesdeDb.NombreCurso = curso.NombreCurso;
                CursoDesdeDb.CantidadClases = curso.CantidadClases;
                CursoDesdeDb.Precio = curso.Precio;
                await _Context.SaveChangesAsync();
                return RedirectToPage("Index");    
            }
            return RedirectToPage();
        }


    }
}

Pages/Cursos/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using AplicacionWebRazor.Data;
using Microsoft.EntityFrameworkCore;

namespace AplicacionWebRazor.Pages.Cursos
{
    public class Index : PageModel
    {
        private readonly AppRazorDbContext _Context;
        public Index(AppRazorDbContext context)
        {
            _Context = context;
        }
        public IEnumerable<Curso> curso {get; set;}

        public async Task OnGet()
        {
            curso = await _Context.cursos.ToListAsync();
        }
         public async Task<IActionResult> OnPostBorrar(int Id)
        {
           
            var curso = await _Context.cursos.FindAsync(Id);
            if (curso == null)
            {
                return NotFound();   
            }
            _Context.cursos.Remove(curso);
            await _Context.SaveChangesAsync();
            return RedirectToPage("Index");     
        }
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AplicacionWebRazor.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AplicacionWebRazor.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AplicacionWebRazor.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

Pages/Cursos/Crear.cshtml
@page
@model AplicacionWebRazor.Pages.Cursos.Crear
@{
    ViewData["Title"] = "Crear nuevo curso";
}

<h1>@ViewData["Title"]</h1>

<div class="card">
    <div class="card-header">
        <h2 class="text-info">Crear un nuevo curso</h2>
    </div>

    <div class="card-body">
       <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="container" style="padding: 30px">
            
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="curso.NombreCurso"></label>
                    </div>
                    <div class="col-sm-6">
                        <input asp-for="curso.NombreCurso"  class="form-control" />
                    </div>
                    <span asp-validation-for="curso.NombreCurso" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="curso.CantidadClases"></label>
                    </div>
                    <div class="col-sm-6">
                        <input asp-for="curso.CantidadClases"  class="form-control" />
                    </div>
                    <span asp-validation-for="curso.CantidadClases" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="curso.Precio"></label>
                    </div>
                    <div class="col-sm-6">
                        <input asp-for="curso.Precio"  class="form-control" />
                    </div>
                    <span asp-validation-for="curso.Precio" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2 offset-sm-2">
                        <input type="submit" value="Crear" class="btn btn-primary form-control" />
                    </div>
                    <div class="col-sm-4">
                        <a asp-page="Index" class="btn btn-success form-control">volver a lista</a>
                    </div>
                </div>
            </div>

        </div>
       </form>
    </div>
</div>

Pages/Cursos/Editar.cshtml
@page
@model AplicacionWebRazor.Pages.Cursos.Editar
@{
    ViewData["Title"] = "Editar curso";
}
<h1>@ViewData["Title"]</h1>

<div class="card">
    <div class="card-header">
        <h2 class="text-info">Crear un nuevo curso</h2>
    </div>

    <div class="card-body">
       <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <!--- Se envia campo oculto --->
        <input type="hidden" asp-for="curso.Id">
        <div class="container" style="padding: 30px">
            
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="curso.NombreCurso"></label>
                    </div>
                    <div class="col-sm-6">
                        <input asp-for="curso.NombreCurso"  class="form-control" />
                    </div>
                    <span asp-validation-for="curso.NombreCurso" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="curso.CantidadClases"></label>
                    </div>
                    <div class="col-sm-6">
                        <input asp-for="curso.CantidadClases"  class="form-control" />
                    </div>
                    <span asp-validation-for="curso.CantidadClases" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="curso.Precio"></label>
                    </div>
                    <div class="col-sm-6">
                        <input asp-for="curso.Precio"  class="form-control" />
                    </div>
                    <span asp-validation-for="curso.Precio" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2 offset-sm-2">
                        <input type="submit" value="Editar" class="btn btn-primary form-control" />
                    </div>
                    <div class="col-sm-4">
                        <a asp-page="Index" class="btn btn-success form-control">volver a lista</a>
                    </div>
                </div>
            </div>

        </div>
       </form>
    </div>
</div>

Pages/Cursos/Index.cshtml
@page
@model AplicacionWebRazor.Pages.Cursos.Index
@{
    ViewData["Title"] = "Mantenimiento de Cursos";
}

<h1>@ViewData["Title"]</h1>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-sm-6">
                <h2 class="text-info">Lista de Cursos</h2>
            </div>
            <div class="col-sm-6">
                <a asp-page="Crear" class="btn btn-primary">Crear nuevo curso</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <form method="Post">
        @if (Model.curso.Count()>0)
        {
            <br/><br/>
            <table class="table table-striped border">
                <tr class="table tablet-secondary">
                    <th class="">@Html.DisplayNameFor(m => m.curso.First().Id)</th>
                    <th class="">@Html.DisplayNameFor(m => m.curso.First().NombreCurso)</th>
                    <th class="">@Html.DisplayNameFor(m => m.curso.First().CantidadClases)</th>
                    <th class="">@Html.DisplayNameFor(m => m.curso.First().Precio)</th>
                    <th class="">@Html.DisplayNameFor(m => m.curso.First().FechaCreacion)</th>
                    <th>Acciones</th>
                </tr>
                @foreach (var item in Model.curso)
                {
                    <tr>
                        <td class="">@Html.DisplayFor(m => item.Id)</td>
                        <td class="">@Html.DisplayFor(m => item.NombreCurso)</td>
                        <td class="">@Html.DisplayFor(m => item.CantidadClases)</td>
                        <td class="">@Html.DisplayFor(m => item.Precio)</td>
                        <td class="">@Html.DisplayFor(m => item.FechaCreacion)</td>
                        <td>
                            <a asp-route-id="@item.Id" asp-page="Editar" class="btn btn-success btn-sm">Editar</a>
                            <button asp-page-handler="Borrar" asp-route-id="@item.Id" onclick="return-confirm{"Esta Seguro de borrar curso?"}" class="btn btn-danger">Eliminar</button>
                        </td>

                    </tr>
                }
            </table>
        }else{
            <p>no hay cursos disponibles</p>
        }
        </form>
    </div>
</div>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AplicacionWebRazor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AplicacionWebRazor.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">AplicacionWebRazor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Cursos/Index">Administración de Cursos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AplicacionWebRazor - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>